### ISSUE TITLE
Cannot follow automatic nor manual setup

### ISSUE THREAD

**Issue by mirenradia** [quexten/bw-bio-handler#4] opened 2023-04-02 08:54 UTC
I tried to follow the automatic setup but when I ran
```
go run . install
```
I got the following output
```
Installing...
Copying polkit policy...
Detecting browsers...
Getting secret...
Enter email: myemail@domain.com
Enter password: 
xxxxxxxxxxxxxxx
Enter api url (leave empty for default): 

Enter identity url (leave empty for default): 

panic: Failed to login: could not login via password: Internal Server Error: 

goroutine 1 [running]:
main.install()
        /home/miren/go/src/github.com/quexten/bw-bio-handler/main.go:93 +0x805
main.main()
        /home/miren/go/src/github.com/quexten/bw-bio-handler/main.go:23 +0x56
exit status 2
```

I then tried the manual setup but when I ran the commmand
```
secret-tool store --label "com.quexten.bitwarden-biometrics-handler-<userid>" --label account <userid>
```
in the browser console (substituting the user-id from the previous step), I got the following error
```
Uncaught SyntaxError: unexpected token: identifier
```

In case it helps, I'm running Fedora 37 KDE and my browser is Firefox 111.0.1.

Any help would be appreciated.

**Comment by quexten** [comment] 2023-04-02 10:55
Thank you for the report. I have reproduced the issue in the automatic setup and will look into it shortly.

About the manual setup, I think I also need to make the instructions more clear. 
This: 

```secret-tool store --label "com.quexten.bitwarden-biometrics-handler-<userid>" --label account <userid> ```

should be run in a terminal on your system, not in the browser. Also it should rather be:
```
secret-tool store --label "com.quexten.bitwarden-biometrics-handler-<userid>" account <userid>
```

For example for a test account of mine I would run:
```
secret-tool store --label 'com.quexten.bitwarden-biometrics-e5b8f18d-cfa2-4384-a141-afd800ade332' account e5b8f18d-cfa2-4384-a141-afd800ade332 
```
And then copy paste in the secret key
```
cm4dmkQQUyyAPVdFwzM2TMkskzh9Om3XcNAA5UagsfM= (without the quotes).
```

**Comment by quexten** [comment] 2023-04-02 11:29
I only previously tested on a self hosted server, the official server seems to behave differently and require a "deviceid". This should be fixed by https://github.com/quexten/bw-bio-handler/pull/5 , so feel free to pull the latest changes and retry the automatic setup and if that does not work now, the updated manual setup, and let me know if either way works for you now :)

**Comment by mirenradia** [comment] 2023-04-02 12:53
Ok, I managed to get the manual setup to work and was able to enable "Unlock with biometrics" in the Bitwarden Firefox browser extension. This seemed to work fine but when I lock the extension and try to unlock it again by clicking on the extension icon, the browser extension box is quickly hidden and a PolicyKit dialog box appears prompting for my fingerprint. My fingerprint seems to be accepted by the dialog box and it disappears but the browser extension continues to be locked and when I click on the icon again, another PolicyKit dialog box appears and the extension box continues to show "Awaiting confirmation from desktop".

**Comment by quexten** [comment] 2023-04-02 13:49
Okay, sorry for the confusion, the manual setup instructions were still incorrect. I tested the manual setup and updated them now.

```
console.log((await this.bitwardenContainerService.cryptoService.getEncKey()).encKeyB64)
```
should rather be
```
console.log((await this.bitwardenContainerService.cryptoService.getKey()).encKeyB64) 
```
(it was the wrong key)

And 
```
secret-tool store --label "com.quexten.bitwarden-biometrics-handler-<userid>" account <userid>
```
should actually be
```
secret-tool store --label "com.quexten.bitwarden-biometrics-handler" account <userid>
```

To fix your setup, clear the previously (incorrectly) stored secret key by running:
```
secret tool clear account <userid>
```

after that do the secret tool related part of the setup again. (Make sure to get the key with the updated command)

**Comment by mirenradia** [comment] 2023-04-02 15:15
Thanks for all the help. That seems to have solved it for me and it now unlocks successfully.

**Comment by quexten** [comment] 2023-04-02 15:27
Glad it works, and thanks for the report. Setup instructions are now much better for any other users!

**Closed as completed by quexten** 2023-04-02 15:27 UTC
